/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package relatorioalunos;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.awt.Robot;

/**
 *
 * @author Leonardo Lima
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    TelaTexto tela;

    private void ExemploRobo() {

        try {      // Instancia a um objeto robot
            Robot robot = new Robot();

            // Pressiona a tecla ENTER
            robot.keyPress(KeyEvent.VK_BACK_SPACE);

        } catch (Exception e) {

            System.err.println("Tem alguma coisa errada que não tá certa!");
        }


    }

    private void exibirInformacao(String info) {
        JOptionPane.showMessageDialog(this, info, "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }

    private boolean validarCampos() {
        if (campoTextoLogin.getText().trim().length() == 0) {
            this.exibirInformacao("O valor do campo 'Login' não foi informado.");
            campoTextoLogin.requestFocus();
            return false;
        }
        if (campoTextoSenha.getText().trim().length() == 0) {
            this.exibirInformacao("O valor do campo 'Senha' não foi informado.");
            campoTextoSenha.requestFocus();
            return false;
        }
        return true;
    }

    public String doEfetuarLogin() {

        String novoLogin = campoTextoLogin.getText().replaceAll(" ", "");
        String novaSenha = campoTextoSenha.getText().replaceAll(" ", "");

        novoLogin = novoLogin.toLowerCase();
        novaSenha = novaSenha.toLowerCase();

        if ("login".equals(novoLogin)
                && "senha".equals(novaSenha)) {
            /* Se escrever o login e senha correto então vai para a tela principal do sistema. */
            this.setVisible(false);
            new TelaTexto().show();
            this.dispose();
        } else {
            this.exibirInformacao("Login ou senha incorretos");
        }

        //Caso erre o login ou senha fica na mesma tela.
        return null;
    }

    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLogin = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        campoTextoLogin = new javax.swing.JTextField();
        botaoOk = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        campoTextoSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelLogin.setText("Login:");

        labelSenha.setText("Senha:");

        campoTextoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoLoginActionPerformed(evt);
            }
        });
        campoTextoLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoTextoLoginKeyPressed(evt);
            }
        });

        botaoOk.setText("OK");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        campoTextoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoSenhaActionPerformed(evt);
            }
        });
        campoTextoSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoTextoSenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLogin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addComponent(botaoOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(botaoCancelar))
                    .addComponent(campoTextoLogin)
                    .addComponent(campoTextoSenha))
                .addGap(47, 47, 47))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin)
                    .addComponent(campoTextoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(campoTextoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.fechar();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void campoTextoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoLoginActionPerformed

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
        validarCampos();
        if (campoTextoSenha.getText().trim().length() != 0 && campoTextoLogin.getText().trim().length() != 0) {
            doEfetuarLogin();
        }
    }//GEN-LAST:event_botaoOkActionPerformed

    private void campoTextoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoSenhaActionPerformed

    private void campoTextoSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validarCampos();
            if (campoTextoSenha.getText().trim().length() != 0 && campoTextoLogin.getText().trim().length() != 0) {
                doEfetuarLogin();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
                this.dispose();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            this.exibirInformacao("A senha é sem espaços.");
            ExemploRobo();
        }

    }//GEN-LAST:event_campoTextoSenhaKeyPressed

    private void campoTextoLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validarCampos();
            if (campoTextoSenha.getText().trim().length() != 0 && campoTextoLogin.getText().trim().length() != 0) {
                doEfetuarLogin();
            }
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
                this.dispose();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            this.exibirInformacao("O login é sem espaços.");
            ExemploRobo();
        }
    }//GEN-LAST:event_campoTextoLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    private void fechar() {
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField campoTextoLogin;
    private javax.swing.JPasswordField campoTextoSenha;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPanel painelLogin;
    // End of variables declaration//GEN-END:variables
}
